### ISSUE TITLE
Bad Cache Hit

### ISSUE THREAD

**Issue by inertia186** [steemit/jussi#197]
Occasionally, jussi appears to mix up cache hits.

I requested:

```json
{  
   "jsonrpc":"2.0",
   "id":178,
   "method":"tags_api.get_tags_used_by_author",
   "params":{  
      "author":"ste emit"
   }
}
```

Note that the author I requested is `ste emit` with a space.  This is part of a test that should respond with an `Author not found` error.  Instead, I got a result from a previous request.

Expected result:

```json
{  
   "jsonrpc":"2.0",
   "error":{  
      "code":-32003,
      "message":"Assert Exception:acnt != nullptr: Author not found",
      "data":{  
         "code":10,
         "name":"assert_exception",
         "message":"Assert 
        Exception",
         "stack":[  
            {  
               "context":{  
                  "level":"error",
                  "file":"tags_api.cpp",
                  "line":99,
                  "method":"get_tags_used_by_author",
                  "hostname":"",
                  "timestamp":"2018-07-17T17:34:11"
               },
               "format":"acnt != nullptr: Author not found",
               "data":{  

               }
            }
         ]
      }
   },
   "id":178
}
```

Actual result:

```json
{"id":178,"jsonrpc":"2.0","result":{"tags":[]}}
```

Here is the full HTTP interaction of the _bad_ result:

Note, there was a cache hit from a previous request where I requested account name `steemit` (without a space):

```
      X-Jussi-Cache-Hit:
      - appbase.tags_api.get_tags_used_by_author.params={'author':'steemit'}
```

```yaml
---
http_interactions:
- request:
    method: post
    uri: https://api.steemit.com/
    body:
      encoding: UTF-8
      string: '{"jsonrpc":"2.0","id":178,"method":"tags_api.get_tags_used_by_author","params":{"author":"ste
        emit"}}'
    headers:
      Content-Type:
      - application/json; charset=utf-8
      User-Agent:
      - steem-ruby/0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      Host:
      - api.steemit.com
      Content-Length:
      - '100'
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 17 Jul 2018 17:16:57 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '47'
      Connection:
      - keep-alive
      Server:
      - nginx
      X-Jussi-Cache-Hit:
      - appbase.tags_api.get_tags_used_by_author.params={'author':'steemit'}
      X-Jussi-Request-Id:
      - '000702687759727855'
      X-Amzn-Trace-Id:
      - Root=1-5b4e2489-36a055665cc6c1a847a3a256
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Headers:
      - DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range
      Strict-Transport-Security:
      - max-age=31557600; includeSubDomains; preload
      Content-Security-Policy:
      - upgrade-insecure-requests
    body:
      encoding: UTF-8
      string: '{"id":178,"jsonrpc":"2.0","result":{"tags":[]}}'
    http_version: 
  recorded_at: Tue, 17 Jul 2018 17:16:57 GMT
recorded_with: VCR 4.0.0
```
